module.exports = {
    // hook related
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    NOT_READY: 'NOT_READY',
    MESSAGE_TOO_OLD: 'MESSAGE_TOO_OLD',
    TIMEOUT: 'TIMEOUT',
    UNKNOWN_ACTION: 'UNKNOWN_ACTION',
    OFFLINE: 'OFFLINE',

    // agent related
    UNKNOWN_AGENT: 'UNKNOWN_AGENT',
    NO_CONNECTED_AGENTS: 'NO_CONNECTED_AGENTS',
    AGENT_NOT_CONNECTED: 'AGENT_NOT_CONNECTED',

    // general
    WRONG_SECRET: 'WRONG_SECRET',
    DUPLICATE_ID: 'DUPLICATE_ID',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};